language: node_js
node_js:
  - node

deploy_service_job: &AWS
  cache:
    directories:
      - node_modules

  install:
    - npm install serverless -g
    - travis_retry npm install

  script:
    - serverless deploy -s ${STAGE}

jobs:
  include:
    # non-master branches deploys to stage named by the branch
    - <<: *AWS
      name: "Deploy DEV"
      if: branch = dev
      env:
        - STAGE="dev"
    - <<: *AWS
        name: "Deploy PROD"
        if: branch = prod
        env:
          - STAGE="prod"