language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install serverless -g
  - travis_retry npm install
jobs:
  include:
    - stage: dev
      name: Deploy DEV
      if: branch = dev
      script: serverless deploy -s dev
    - stage: prod
      name: Deploy PROD
      if: branch = master
      script: serverless deploy -s prod