language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: devDeploy
    - script: npm install -g serverless
    - script: sls deploy --stage dev

    - stage: prodDeploy
    - script: npm install -g serverless
    - script: sls deploy --stage prod

stages:
  - name: devDeploy
    if: branch = dev
  - name: prodDeploy
    if: branch = master