service: moose

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 10
  stage: dev
  region: eu-central-1
  environment:
    DB: ${file(env.yml):${self:provider.stage}.DB}
    DB_USER: ${file(env.yml):${self:provider.stage}.DB_USER}
    DB_PASS: ${file(env.yml):${self:provider.stage}.DB_PASS}
    DB_PORT: ${file(env.yml):${self:provider.stage}.DB_PORT}
    DB_NAME: ${file(env.yml):${self:provider.stage}.DB_NAME}
    MAIL: ${file(env.yml):${self:provider.stage}.MAIL}
    SECRET: ${file(env.yml):${self:provider.stage}.SECRET}

functions:
  auth:
    handler: auth/token.auth
  signup:
    handler: signup/handler.signup
    events:
      - http:
          path: api/signup
          method: post
          cors: true
  register:
    handler: auth/handler.register
    events:
      - http:
          path: api/register
          method: post
          cors: true
          authorizer: auth #TODO: Remove in prod, but prevent registration from happening
  login:
    handler: auth/handler.login
    events:
      - http:
          path: api/login
          method: post
          cors: true
  me:
    handler: auth/handler.me
    events:
      - http:
          path: api/me
          method: get
          cors: true
          authorizer: auth

plugins:
  - serverless-offline
#  - serverless-bundle
#  - serverless-domain-manager

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'

#custom:
#  customDomain:
#    domainName: api.moosehour.com
#    basePath: "/"
#    createRoute53Record: false