service: moose

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  timeout: 10
  stage: prod
  region: us-east-1
  environment:
    MAIL_HOST: ${file(env.yml):${self:provider.stage}.MAIL_HOST}
    MAIL_PORT: ${file(env.yml):${self:provider.stage}.MAIL_PORT}
    MAIL_USER: ${file(env.yml):${self:provider.stage}.MAIL_USER}
    MAIL_PASS: ${file(env.yml):${self:provider.stage}.MAIL_PASS}
    MAIL_SERVICE: ${file(env.yml):${self:provider.stage}.MAIL_SERVICE}

functions:
  sendMail:
    handler: mail.sendMail
    events:
      - http:
          path: api/signup
          method: post
          cors: true
  verifyMail:
    handler: mail.verifyMail

plugins:
  - serverless-offline
#  - serverless-bundle
#  - serverless-domain-manager

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

#custom:
#  customDomain:
#    domainName: api.moosehour.com
#    basePath: "/"
#    createRoute53Record: false